# Generated by Django 2.2.2 on 2019-07-01 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('gender', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('debt', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Задолженность')),
                ('status_of_work_with_debt', models.CharField(blank=True, choices=[('Не начата', 'Не начата'), ('В процессе', 'В процессе')], max_length=255, null=True, verbose_name='Статус работы по взысканию задолженности')),
                ('garbage_payment', models.BooleanField(choices=[(True, 'Оплачено'), (False, 'Нет')], null=True, verbose_name='Задолженность по мусору')),
                ('date_of_issue', models.DateField(null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_date', models.DateField(null=True, verbose_name='Дата выдачи')),
                ('passport_series', models.IntegerField(null=True, verbose_name='Серия паспорта')),
                ('passport_id', models.IntegerField(null=True, verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(max_length=100, null=True, verbose_name='Кем выдан')),
                ('unit_code', models.IntegerField(null=True, verbose_name='Код подразделения')),
                ('type_of_passport', models.CharField(choices=[('РФ', 'РФ'), ('Загран', 'Загран')], max_length=100, null=True, verbose_name='Тип паспорта')),
                ('birthday_reminder', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Напоминание о Дне Рождения')),
                ('hard_case', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Проблемный')),
                ('loyal', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Лояльный')),
                ('vip', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='VIP')),
                ('calls', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Звонки')),
                ('sms', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='СМС')),
                ('mail', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Email')),
                ('comments', models.TextField(null=True, verbose_name='Комментарий')),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('dead', 'Dead')], max_length=255, null=True, verbose_name='Status of Lead')),
                ('source', models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('existing customer', 'Existing Customer'), ('partner', 'Partner'), ('public relations', 'Public Relations'), ('compaign', 'Campaign'), ('other', 'Other')], max_length=255, null=True, verbose_name='Source of Lead')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Opportunity Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('is_active', models.BooleanField(default=False)),
                ('enquery_type', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leads', to='accounts.Account')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadaddress', to='common.Address')),
                ('assigned_to', models.ManyToManyField(related_name='lead_assigned_users', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_created_by', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(to='common.Team')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
