# Generated by Django 2.2.2 on 2019-07-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_created_by'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='apartments',
            field=models.ManyToManyField(related_name='apartments', to='apartments.Apartment'),
        ),
    ]
