# Generated by Django 2.2.2 on 2019-07-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_apartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='apartments',
            field=models.ManyToManyField(related_name='owners', to='apartments.Apartment'),
        ),
    ]
