# Generated by Django 2.2.6 on 2019-10-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.PositiveSmallIntegerField(verbose_name='№ помещения')),
                ('entrance', models.PositiveSmallIntegerField(verbose_name='Подъезд')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('number_of_rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('number_of_business_account', models.PositiveIntegerField(unique=True, verbose_name='№ лицевого счёта')),
                ('balance_of_business_account', models.IntegerField(default=0, verbose_name='Баланс лицевого счёта')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='Изменено')),
                ('type', models.CharField(choices=[('Жилое', 'Жилое'), ('Нежилое', 'Нежилое')], default='Нежилое', max_length=64, verbose_name='Тип помещения')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['created_on'],
            },
        ),
    ]
