# Generated by Django 2.2.2 on 2019-06-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.PositiveSmallIntegerField(verbose_name='Подъезд')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('number_of_rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address')),
                ('business_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.BusinessAccount')),
            ],
        ),
    ]
