# Generated by Django 2.2.2 on 2019-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Не заселена', 'Не заселена'), ('Заселена', 'Заселена')], default='Не заселена', max_length=64, verbose_name='Статус'),
        ),
    ]
