# Generated by Django 2.2.2 on 2019-06-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20190630_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_number',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Номер квартиры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address'),
        ),
    ]
