# Generated by Django 2.2.2 on 2019-06-30 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20190630_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
