# Generated by Django 2.2.2 on 2019-08-02 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('industry', models.CharField(blank=True, choices=[('Электрик', 'Электрик'), ('Сантехник', 'Сантехник'), ('Слесарь', 'Слесарь'), ('Слаботочник', 'Слаботочник'), ('Охранник', 'Охранник')], max_length=255, null=True, verbose_name='Тип деятельности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Добавлен')),
                ('is_active', models.BooleanField(default=False, verbose_name='Свободен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
