# Generated by Django 2.2.4 on 2019-08-16 13:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('occupation', models.CharField(blank=True, choices=[('Электрик', 'Электрик'), ('Сантехник', 'Сантехник'), ('Слесарь', 'Слесарь'), ('Слаботочник', 'Слаботочник'), ('Охранник', 'Охранник')], max_length=255, null=True, verbose_name='Тип деятельности')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=False, verbose_name='Свободен')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['-created_on'],
            },
        ),
    ]
