# Generated by Django 2.2 on 2019-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
