# Generated by Django 2.2.6 on 2019-10-25 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('apartments', '0002_apartment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('Физ. лицо', 'Физ. лицо'), ('Юр. лицо', 'Юр. лицо')], default='Физ. лицо', max_length=10, verbose_name='Тип клиента')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не указан', 'Не указан')], default='Не указан', max_length=10, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('car_numbers', models.CharField(blank=True, max_length=2000, verbose_name='Номера автомобилей')),
                ('registration', models.CharField(max_length=2000, verbose_name='Место регистрации')),
                ('passport', models.CharField(blank=True, max_length=5000, verbose_name='Паспортные данные')),
                ('calls', models.BooleanField(verbose_name='Звонки')),
                ('sms', models.BooleanField(verbose_name='СМС')),
                ('mail', models.BooleanField(verbose_name='Email')),
                ('apartments', models.ManyToManyField(blank=True, related_name='client', to='apartments.Apartment')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-date_joined'],
            },
            bases=('users.user',),
        ),
    ]
