# Generated by Django 2.2.6 on 2019-10-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='apartments',
            field=models.ManyToManyField(related_name='client', to='apartments.Apartment'),
        ),
    ]
