# Generated by Django 2.2.2 on 2019-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190415_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
