# Generated by Django 2.2.4 on 2019-08-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_apartment_created_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Телефон')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('debt', models.BooleanField(null=True, verbose_name='Задолженность')),
                ('status_of_work_with_debt', models.CharField(blank=True, choices=[('Не начата', 'Не начата'), ('В процессе', 'В процессе')], max_length=255, null=True, verbose_name='Статус работы по взысканию задолженности')),
                ('garbage_payment', models.BooleanField(choices=[(True, 'Оплачено'), (False, 'Нет')], null=True, verbose_name='Задолженность по мусору')),
                ('date_of_issue', models.DateField(null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_date', models.DateField(null=True, verbose_name='Дата выдачи')),
                ('passport_series', models.IntegerField(null=True, verbose_name='Серия паспорта')),
                ('passport_id', models.IntegerField(null=True, verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(max_length=100, null=True, verbose_name='Кем выдан')),
                ('unit_code', models.IntegerField(null=True, verbose_name='Код подразделения')),
                ('type_of_passport', models.CharField(choices=[('РФ', 'РФ'), ('Заграничный', 'Заграничный')], max_length=100, null=True, verbose_name='Тип паспорта')),
                ('birthday_reminder', models.BooleanField(verbose_name='Напоминание о Дне Рождения')),
                ('hard_case', models.BooleanField(verbose_name='Проблемный')),
                ('loyal', models.BooleanField(verbose_name='Лояльный')),
                ('vip', models.BooleanField(verbose_name='VIP')),
                ('calls', models.BooleanField(verbose_name='Звонки')),
                ('sms', models.BooleanField(verbose_name='СМС')),
                ('mail', models.BooleanField(verbose_name='Email')),
                ('apartments', models.ManyToManyField(blank=True, related_name='homeowner', to='apartments.Apartment')),
            ],
            options={
                'verbose_name': 'Собственник',
                'verbose_name_plural': 'Собственники',
                'ordering': ['-date_joined'],
            },
            bases=('users.user',),
        ),
    ]
