# Generated by Django 2.2.6 on 2019-10-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Заявление на застройщика', 'Заявление на застройщика'), ('Акт осмотра', 'Акт осмотра'), ('Акт приема-передачи документов и ключей', 'Акт приема-передачи документов и ключей'), ('Договор возмездного оказания услуг', 'Договор возмездного оказания услуг'), ('Соглашение об отсутствии общественного транспорта на территории ЖК', 'Соглашение об отсутствии общественного транспорта на территории ЖК'), ('Согласие на обр.перс.данных', 'Согласие на обр.перс.данных'), ('Гарантийное письмо', 'Гарантийное письмо')], max_length=200, verbose_name='Тип документа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attachment', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='Прикрепления')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='Изменено')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apartments.Apartment')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['created_on'],
            },
        ),
    ]
