# Generated by Django 2.2.4 on 2019-08-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Запланировано', 'Запланировано'), ('Новая', 'Новая'), ('В работе', 'В работе'), ('Завершено', 'Завершено'), ('Отменено', 'Отменено')], default='Новая', max_length=64, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], default='Средняя', max_length=64, verbose_name='Приоритет')),
                ('request_type', models.CharField(blank=True, choices=[('Сантехник', 'Сантехник'), ('Электрик', 'Электрик'), ('House master', 'House master'), ('Уборщик', 'Уборщик'), ('Слаботочник', 'Слаботочник'), ('Прочее', 'Прочее')], default='Прочее', max_length=255, null=True, verbose_name='Тип заявки')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='Закрыта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='Изменено')),
                ('is_proceed', models.BooleanField(default=False, verbose_name='В работе')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.Apartment')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_on'],
            },
        ),
    ]
