# Generated by Django 2.2.2 on 2019-08-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_created_by'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.Apartment'),
            preserve_default=False,
        ),
    ]
