# Generated by Django 2.2.4 on 2019-08-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeowners', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homeowners.Homeowner'),
        ),
        migrations.AddField(
            model_name='request',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='request', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
