# Generated by Django 2.2.2 on 2019-07-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_on'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='request',
            name='closed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_proceed',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(blank=True, choices=[('Электрооборудование', 'Электрооборудование'), ('Сантехника', 'Сантехника'), ('Уборщик', 'Уборщик'), ('Прочее', 'Прочее')], default='Прочее', max_length=255, null=True, verbose_name='Тип заявки'),
        ),
    ]
