# Generated by Django 2.2.4 on 2019-08-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(blank=True, choices=[('Сантехник', 'Сантехник'), ('Электрик', 'Электрик'), ('House master', 'House master'), ('Уборщик', 'Уборщик'), ('Слаботочник', 'Слаботочник'), ('Прочее', 'Прочее')], default='Прочее', max_length=255, null=True, verbose_name='Тип заявки'),
        ),
    ]
