# Generated by Django 2.2.2 on 2019-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20190725_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='request', to='staff.Staff'),
        ),
    ]
