# Generated by Django 2.2.6 on 2019-10-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20191025_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='request', to='staff.Staff', verbose_name='Исполнители'),
        ),
    ]
