# Generated by Django 2.2.2 on 2019-08-02 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_str', models.CharField(max_length=500, verbose_name='Адрес')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=1000, verbose_name='Группа услуг')),
                ('debt_at_beg_of_period', models.FloatField(verbose_name='Задолженность на начало периода')),
                ('accrued', models.FloatField(verbose_name='Начислено')),
                ('recalculations', models.FloatField(verbose_name='Перерасчёты')),
                ('paid', models.FloatField(verbose_name='Оплачено')),
                ('debt_at_end_of_period', models.FloatField(verbose_name='Задолженность на конец периода')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
