# Generated by Django 2.2.4 on 2019-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Москва', 'Москва')], max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=500, verbose_name='Улица')),
                ('building', models.CharField(max_length=50, verbose_name='Здание')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['-created_on'],
            },
        ),
    ]
