# Generated by Django 2.2.2 on 2019-06-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessAccount',
        ),
    ]
